In [6]:
#import library yang diperlukan(numpy, pandas, seaborn, matplotlib)
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib

In [5]:
df= pd.read_csv("tech_fundings.csv")
df

,index,Company,Website,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
0,1,Internxt,https://internxt.com/,Spain,Blockchain,278940,Seed,Jan-20
1,2,Dockflow,https://dockflow.com,Belgium,Logistics,292244,Seed,Jan-20
2,3,api.video,https://api.video,France,Developer APIs,300000,Seed,Jan-20
3,4,Buck.ai,https://buck.ai/,United States,Artificial Intelligence,300000,Seed,Jan-20
4,5,Prodsight,https://www.prodsight.ai,United Kingdom,Artificial Intelligence,529013,Seed,Jan-20
...,...,...,...,...,...,...,...,...
3570,3571,Headout,https://www.headout.com,United States,Travel,12000000,Series B,Sep-21
3571,3572,OLIO,https://olioex.com/,United Kingdom,Wellness,43000000,Series B,Sep-21
3572,3573,Trees for Life,https://treesforlife.org.uk,United Kingdom,Wellness,2737468,Crowdfunding,Sep-21
3573,3574,Britishvolt,https://britishvolt.com/,United Kingdom,Wellness,70000000,Series B,Sep-21
3574,3575,Greenly,https://www.greenly.earth/,France,Wellness,2953675,Seed,Sep-21

In [11]:
#periksa type datanya terlebih dahulu
df.dtypes

index                    int64
Company                 object
Website                 object
Region                  object
Vertical                object
Funding Amount (USD)    object
Funding Stage           object
Funding Date            object
dtype: object

In [14]:
#periksa apakah data ada yang kosong
df.isnull().sum()

index                    0
Company                  0
Website                  0
Region                  12
Vertical                 0
Funding Amount (USD)     0
Funding Stage            0
Funding Date             0
dtype: int64

In [15]:
df.tail(10)

,index,Company,Website,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
3565,3566,Volta Trucks,https://voltatrucks.com/,Sweden,Transportation,43334400,Series B,Sep-21
3566,3567,WestConnex,https://www.westconnex.com.au/,Australia,Transportation,16600000000,Private Equity,Sep-21
3567,3568,BluSmart Mobility,https://www.blu-smart.com/,India,Transportation,24896631,Series A,Sep-21
3568,3569,StreetDrone,https://www.streetdrone.com,United Kingdom,Transportation,4113750,Series A,Sep-21
3569,3570,SmarterTravel,https://www.smartertravel.com/,United States,Travel,9500000,Series B,Sep-21
3570,3571,Headout,https://www.headout.com,United States,Travel,12000000,Series B,Sep-21
3571,3572,OLIO,https://olioex.com/,United Kingdom,Wellness,43000000,Series B,Sep-21
3572,3573,Trees for Life,https://treesforlife.org.uk,United Kingdom,Wellness,2737468,Crowdfunding,Sep-21
3573,3574,Britishvolt,https://britishvolt.com/,United Kingdom,Wellness,70000000,Series B,Sep-21
3574,3575,Greenly,https://www.greenly.earth/,France,Wellness,2953675,Seed,Sep-21

In [16]:
###mengapus kolom data yang tidak digunakan###

In [18]:
#menghapus kolom index karena tidak digunakan
df.drop(columns=["index"], inplace=True)

In [19]:
#menghapus kolom website karena tidak digunakan
df.drop(columns=["Website"], inplace=True)

In [20]:
df.head(10)

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
0,Internxt,Spain,Blockchain,278940,Seed,Jan-20
1,Dockflow,Belgium,Logistics,292244,Seed,Jan-20
2,api.video,France,Developer APIs,300000,Seed,Jan-20
3,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
4,Prodsight,United Kingdom,Artificial Intelligence,529013,Seed,Jan-20
5,Harvestr,France,B2B Software,650000,Angel,Jan-20
6,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
7,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
8,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
9,Prisync,Turkey,B2B Software,1100000,Seed,Jan-20

In [ ]:
#filter data untuk perusahaan  yang diberikan pendanaan di negara united state

In [23]:
df2=df.query("Region == 'United States'")
df2.head(10)

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
3,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
6,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
7,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
8,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
10,Fundraise Up,United States,B2B Software,1250000,Seed,Jan-20
11,Yac,United States,B2B Software,1250000,Seed,Jan-20
12,Cloverleaf.me,United States,Human Resources,1300000,Seed,Jan-20
13,Docket,United States,B2B Software,1500000,Seed,Jan-20
14,Podsights,United States,Marketing,1500000,Seed,Jan-20
15,SIMBA Chain,United States,Blockchain,1500000,Seed,Jan-20

In [25]:
df2.to_csv('Company Fundings US.csv', index=False)
df2 = pd.read_csv('Company Fundings US.csv')
df2

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
0,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
1,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
2,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
3,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
4,Fundraise Up,United States,B2B Software,1250000,Seed,Jan-20
...,...,...,...,...,...,...
2029,Locus Robotics,United States,Robotics,50000000,Series E,Sep-21
2030,Discord,United States,Social Network,500000000,Series H,Sep-21
2031,Qwilt,United States,Telecommunications,70000000,Series E,Sep-21
2032,SmarterTravel,United States,Travel,9500000,Series B,Sep-21
2033,Headout,United States,Travel,12000000,Series B,Sep-21